import React from "react";

function Services() {
    return(
        <div className="services-div">
            <p className="services-heading">SERVICES</p>
            <p className="services-heading-2">Our services can be classified into 3 major categories.</p>
            <div className="row services">
                <div className="service col-md-4 col-lg-4"><div><div className="service-div">Experiment Files</div><p className="service-div-p">Whether it is the science experiments in class 6 or class 12, or even in the undergraduate degree of B.Tech, experiment files are often an unnecessary hassle. With copying pages and pages of information from reference books to files with intricate diagrams, they often take innumerable hours or all-nighters forcing students to sacrifice their sleep and time. As experienced experiment file makers, we offer easy, and cost-effective solutions, with pricing based on per experiment, exclusive of any postal charges. In the case of online typed files & documents, the costing will be converted to a per word basis. Moreover, the ideal delivery period will vary between 5-7 days, exclusive of any postal delays. If you desire a shorter waiting period, there will be additional costs. For further customizations & enquiries, contact our college experiment file makers today!</p></div></div>
                <div className="service col-md-4 col-lg-4"><div><div className="service-div">Assignments</div><p className="service-div-p">Struggling with research and framing of your school assignment, or having trouble juggling that 2000 word college assignment with other responsibilities? We have got your back! Whether it is elementary grades or undergraduate degrees we offer assignment solutions to all. As seasoned school assignment makers, we aim to deliver quality, well-researched and documented, cost-effective solutions to all our customers.
Keeping in line with board and university-issued guidelines in the case of college counterparts, pre-researched assignments are offered discounted prices alongside a shorter waiting period of 5 days, exclusive of postal delays. Nonetheless, we don’t shy away from research & if the same is required for maintaining the quality of content offered, clients have to incur additional costs with waiting periods extended by 2 days. Moreover, keeping the pandemic models in mind, in case of typed assignments & school reports, the students are charged on a per word basis with the same being delivered in their inbox within 4 days, however, research conditions stand as a blanket condition for all.</p></div></div>
                <div className="service col-md-4 col-lg-4"><div><div className="service-div">Summer Projects</div><p className="service-div-p">Struggling with a summer break project? Or is that one last-minute long presentation eating away at precious time in your mid-semester break? We have got you! Whether it is an elementary grade chart, middle school decorative project file, board submission in class 10 or 12 or even a mid-semester presentation slides accounting for a significant percentage of your final grade, we offer it all. As seasoned school project makers, we offer both simple as well as intricate & extravagant project & presentation models, all tailored to the needs & wants of each student without compromising on quality, cost-effectiveness or punctuality of delivery while keeping in mind the various CBSE/ICSE or state board standards. Nonetheless, in case students want to impress & score extra marks with calligraphic tiles, 3D cover pages & folders or further artistic customizations, they will have to incur extra charges for the same. As experienced college project makers, we never shy away from research, but if the same is required for any presentation a base cost is added, alongside a two-day extension to the normal 5-7 day waiting period, exclusive of postal delays. For, typed counterparts, the charges will be on a per word basis. Moreover, depending on the length of project files & presentation files, the prices may vary</p></div></div>
            </div>
            {/* <hr></hr> */}
        </div>
    );
}

export default Services;